### ISSUE TITLE
How to apply RandAug to ImageNet

### ISSUE THREAD

**Issue by d-li14** [open-mmlab/mmclassification#218]
@LXXXXR Thanks for implementing RandAug. Could you please provide the config of RandAug policies applied to ResNet on ImageNet?

**Comment by LXXXXR** [comment]
We will release the RandAug policies with ResNest training config, which shall be in this month.

**Comment by d-li14** [comment]
Hi @LXXXXR 
Thanks for your contribution. But to my knowledge, the original ResNeSt is reported to be trained with AutoAug. Does it mean you will train it with the RandAug on ImageNet?

**Comment by LXXXXR** [comment]
Yes, we will follow the training set here: https://hangzhang.org/PyTorch-Encoding/model_zoo/imagenet.html

**Comment by d-li14** [comment]
Got it, look forward to the RandAug implementation results in the near future.

**Comment by d-li14** [comment]
@LXXXXR I notice that the RandAug config of ResNeSt training is not included in the monthly update as aforementioned. Do you have a schedule for that?

**Comment by 24hours** [comment]
```yaml
train_pipeline:
  - type: LoadImageFromFile
  - type: RandomResizedCrop
    size: 224
  - type: RandomFlip
    flip_prob: 0.5
    direction: horizontal
  - type: RandAugment
    num_policies: 14
    magnitude_level: 15
    policies:
      - type: Rotate
        magnitude_key: angle
        magnitude_range: [-30, 30]
        prob: 1
      - type: AutoContrast
      - type: Equalize
      - type: Solarize
        magnitude_key: thr
        magnitude_range: [0, 256]
        prob: 1
      - type: SolarizeAdd
        magnitude_key: magnitude
        magnitude_range: [0, 110]
        prob: 1
      - type: ColorTransform
        magnitude_key: magnitude
        magnitude_range: [0.1, 1.9]
        prob: 1
      # - type: posterize
      #   magnitude_key: bits
      #   magnitude_range: [0, 4]
      #   prob: 1
      - type: Contrast
        magnitude_key: magnitude
        magnitude_range: [0.1, 1.9]
        prob: 1
      - type: Brightness
        magnitude_key: magnitude
        magnitude_range: [0.1, 1.9]
        prob: 1
      - type: Sharpness
        magnitude_key: magnitude
        magnitude_range: [0.1, 1.9]
        prob: 1
      - type: Shear
        magnitude_key: magnitude
        magnitude_range: [0, 0.3]
        direction: horizontal
        prob: 1
      - type: Shear
        magnitude_key: magnitude
        magnitude_range: [0, 0.3]
        direction: vertical
        prob: 1
      - type: Translate        
        magnitude_key: magnitude
        magnitude_range: [-0.45, 0.45]
        direction: horizontal
        prob: 1
      - type: Translate        
        magnitude_key: magnitude
        magnitude_range: [-0.45, 0.45]
        direction: vertical
        prob: 1
  - type: Normalize
    mean: ${img_norm.mean}
    std: ${img_norm.std}
    to_rgb: ${img_norm.to_rgb}
  - type: ImageToTensor
    keys: ['img']
  - type: ToTensor
    keys: ['gt_label']
  - type: Collect
    keys: ['img', 'gt_label']
```

I have created my own pipeline referencing to original paper.
