### ISSUE TITLE
Can dataset_type:imagenet work without ann_file?

### ISSUE THREAD

**Issue by wolfryu** [open-mmlab/mmclassification#869]
**Checklist**
I have searched related issues but cannot get the expected help.
I have read related documents and don't know what to do.
**Describe the question you meet**

my data folder is this:

```
data:
      mydata:
                train:
                       dogs: 1.png ....
                       cats: 100.png ....
                val:
                       dogs: 2.png ....
                       cats: 200.png ....
                test:
                       dogs: 3.png ....
                       cats: 300.png ....
                classes.txt
```

in my config file, I set data as this:
```
data = dict(
    # Specify the batch size and number of workers in each GPU.
    # Please configure it according to your hardware.
    samples_per_gpu=32,
    workers_per_gpu=2,
    # Specify the training dataset type and path
    train=dict(
        type=dataset_type,
        data_prefix='data/mydata/train',
        classes='data/mydata/classes.txt',
        pipeline=train_pipeline),
    # Specify the validation dataset type and path
    val=dict(
        type=dataset_type,
        data_prefix='data/mydata/val',
        # ann_file='data/cats_dogs_dataset/val.txt',
        classes='data/mydata/classes.txt',
        pipeline=test_pipeline),
    # Specify the test dataset type and path
    test=dict(
        type=dataset_type,
        data_prefix='data/mydata/test',
        # ann_file='data/cats_dogs_dataset/test.txt',
        classes='data/mydata/classes.txt',
        pipeline=test_pipeline))
```

this config can do the training, so imagenet can work without annotation txt file and judge the class by folder name?
Is that right?
